// <auto-generated />
namespace Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddOpenTimetoTickets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOpenTimetoTickets));
        
        string IMigrationMetadata.Id
        {
            get { return "201712140026436_Add-OpenTime-toTickets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
